remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: "Cats of NLP"
tagline: "Feline friends hard at work in the NLP lab."
description: "The cats of NLP research! Feline friends hard at work in the lab, or emotional support during CUDA OOM errors. Ragdolls who love the RSA model, Persians who model phrase structure, and tabbies who train transformers!"
locale: "en-us"
logo: "https://catsofnlp.github.io/images/logo.jpg"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

