remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: "Cats of NLP"
locale: "en-us"
logo: "https://catsofnlp.github.io/images/logo.jpg"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
